name: deploy-mobile-android-to-firebase-app-distribution

on:
  pull_request:
    branches:
      - staging
    types:
      - closed
jobs:
  build:
    name: android build
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: 'actions/checkout@v3'

      - name: set up JDK 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  

      - name: Install Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.3.7'
          channel: 'stable'

      - name: Google login
        uses: google-github-actions/auth@v1.0.0
        with:
          credentials_json: ${{ secrets.GCP_SA_CREDENTIALS }}

      - name: Setup Cloud SDK(gcloud)
        uses: google-github-actions/setup-gcloud@v1

      - name: Add google-services.json for Firebase
        run: gcloud secrets versions access latest --secret="prod-env-mobile-android-firebase-json" > mobile/android/app/google-services.json
        
      - name: Set up keystore files
        run: |
          cd mobile/android/
          gcloud secrets versions access latest --secret="sta-env-mobile-airqo-dev-keystore-encrypted" | base64 -di > app/airqo-dev-keystore.jks
          gcloud secrets versions access latest --secret="prod-env-mobile-upload_keystore_encrypted" | base64 -di > app/upload-keystore.jks


      - name: Create key.properties files
        run: |
          cd mobile/android/
          gcloud secrets versions access latest --secret="prod-key-mobile-CI" > prod-key.properties
          gcloud secrets versions access latest --secret="sta-key-mobile-ci" > key.properties

      - name: Add firebase options files
        run: |
          cd mobile/lib/
          gcloud secrets versions access latest --secret="prod-env-mobile-firebase_optionsDev" > firebase_options_dev.dart
          gcloud secrets versions access latest --secret="prod-env-mobile-firebase_options" > firebase_options.dart

      - name: Add .env files
        run: |
          cd mobile/
          gcloud secrets versions access latest --secret="prod-env-mobile-app" > .env.prod
          gcloud secrets versions access latest --secret="sta-env-mobile-app" > .env.dev

      - name: Build app
        run: |
          cd mobile/
          flutter pub get
          flutter build appbundle --flavor airqo

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle
          path: mobile/build/app/outputs/bundle/airqoRelease/app-airqo-release.aab
          retention-days: 1
      
      - name: Add firebase app distribution service and play store service account
        run: |
          cd mobile/android/
          gcloud secrets versions access latest --secret="prod-env-mobile-firebase-app-distribution" | base64 --decode > firebase_distributor.json
          gcloud secrets versions access latest --secret="prod-env-mobile-play-store-service-account-encrypted" | base64 --decode > play_store_SA.json


      - name: Add app testers
        run: |
          cd mobile/android/
          gcloud secrets versions access latest --secret="prod-env-mobile-testers-android"  > testers.txt

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1.123.0
        with:
          ruby-version: "2.6"
          working-directory: mobile/android
      
      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        working-directory: mobile/android
          
      - name: Deploy to app distribution
        run: 
          bundle exec fastlane android distribute
        env:
          MOBILE_ANDROID_ID_FIREBASE: ${{secrets.MOBILE_ANDROID_ID_FIREBASE}}
        working-directory: mobile/android
        







